#! /usr/bin/env python

from mutrans.run import *
import argparse

parser = argparse.ArgumentParser(prog = "mutrans")

parser.add_argument("--version", action = "version", version = "mutrans-0.1.0")

parser.add_argument("mutation_file", metavar = "mutation.vcf.gz", default = None, type = str,
                    help = "the path to the mutation file")

parser.add_argument("junction_file", metavar = "junction.bed", default = None, type = str,
                    help = "the path to the splicing junction file")

parser.add_argument("output_prefix", metavar = "output_prefix", default = None, type = str, 
                    help = "the prefix of the output")

parser.add_argument("param", metavar = "param.cfg", default = None, type = str,
                    help = "parameter information file (to be parsed by ConfigParser module)")

parser.add_argument('-f', choices=['vcf', 'anno'], default = 'vcf',
                    help = "the format of mutation file vcf or annovar (tsv) format")

parser.add_argument("--ctrl", metavar = "control_file", default = None, type = str,
                    help = "the path to the control panel junction")

args = parser.parse_args()

main(args)

